ColorPicker
gmfe/gmfe pull request #51
Opened 2020-04-14 07:08 UTC by electhuang

2020-04-14 07:20 UTC, LaamGinghong requested changes
提了几点

2020-04-14 07:20 UTC, LaamGinghong commented on packages/react/src/component/color_picker/index.js
> +    this.props.onConfirm(this.state.color)
判断onConfirm，因为你的props 没有设置为必填

2020-04-14 07:20 UTC, LaamGinghong commented on packages/react/src/component/color_picker/index.js
> +      color: props.color || '#ffffff'
这个讲道理设置成defaultProps就好了，不需要 ||

2020-04-14 07:20 UTC, LaamGinghong commented on packages/react/src/component/color_picker/index.js
> +      color: props.color || '#ffffff'
而且，如果组件是非受控的，color建议命名为defaultColor

2020-04-14 07:49 UTC, noledjokovic commented on packages/react/src/component/color_picker/index.js
> +  color: '#ffffff',
这里有默认props，上面的应该可以去掉

2020-04-14 07:56 UTC, chaoming56 commented on packages/react/src/component/color_picker/index.js
> +          <Button block onClick={onCancel}>
onCancel 有可能是undefined

2020-04-14 08:23 UTC, noledjokovic commented on packages/react/src/component/color_picker/index.js
> +  color: '#ffffff',
这里已有默认props

2020-04-15 02:08 UTC, LaamGinghong approved these changes
pass

2020-04-15 02:09 UTC, noledjokovic approved these changes

2020-04-20 02:39 UTC, merged