after index change
gmfe/gmfe pull request #64
Opened 2020-04-27 04:02 UTC by tubulang

2020-04-30 03:25 UTC, LaamGinghong commented
合了代码要跟我说，我看你修改记录里面更改了组件的props @tubulang

2020-04-30 04:19 UTC, LaamGinghong requested changes

2020-04-30 04:19 UTC, LaamGinghong commented on packages/react/src/component/carousel/carousel.js
> +  _countArray.length = count
每次都生成一个新的数组，虽然使用场景大概率count不会变，但是应该有优化的空间

2020-04-30 04:19 UTC, LaamGinghong commented on packages/react/src/component/carousel/carousel.js
> +  transitionTime: PropTypes.number.isRequired,
这个应该可以给个默认值吧

2020-04-30 04:19 UTC, LaamGinghong commented on packages/react/src/component/carousel/carousel.js
> +  currentIndex: PropTypes.number.isRequired
这个同理

2020-04-30 06:18 UTC, tubulang commented on packages/react/src/component/carousel/carousel.js
> +  transitionTime: PropTypes.number.isRequired,
没有必要给，必须得父组件传，已经required了

2020-05-07 04:01 UTC, CyberDamon commented on packages/react/src/component/carousel/carousel.js
> +  const handleCancelSelect = () => {
useCallback,报一下是不是性能更好?

2020-05-07 04:01 UTC, CyberDamon commented on packages/react/src/component/carousel/carousel.js
> +  _countArray.length = count
const _countArray = React.useMemo( () => _.range(count), [count])

2020-05-07 04:01 UTC, chaoming56 commented on packages/react/src/component/carousel/carousel.js
> +  _countArray.length = count
const _countArrary = _.range(count) 这样更简洁?

2020-05-07 04:03 UTC, chaoming56 commented on packages/react/src/component/carousel/carousel.js
> +  onAfterChange: PropTypes.func,
onAfterChange 貌似有语病
你是想表达 onIndexChange 吧?

2020-05-13 02:20 UTC, tubulang commented on packages/react/src/component/carousel/carousel.js
> +  _countArray.length = count
生成新的会有什么影响吗，我看这里是没有什么区别的

2020-05-13 02:20 UTC, tubulang commented on packages/react/src/component/carousel/carousel.js
> +  _countArray.length = count
> const _countArrary = _.range(count) 这样更简洁?

好像可以

2020-05-13 02:20 UTC, tubulang commented on packages/react/src/component/carousel/carousel.js
> +  _countArray.length = count
> const _countArray = React.useMemo( () => _.range(count), [count])

没有必要做useMemo，useMemo本身也是有性能耗损，这里没有什么性能耗损过大的地方，因此感觉不需要加

2020-05-13 02:20 UTC, tubulang commented on packages/react/src/component/carousel/carousel.js
> +  const handleCancelSelect = () => {
同useMemo

2020-05-13 02:20 UTC, tubulang commented on packages/react/src/component/carousel/carousel.js
> +  onAfterChange: PropTypes.func,
afterChange就是在index change之后执行，改成onIndexChange也行

2020-05-13 04:12 UTC, LaamGinghong approved these changes

2020-05-13 06:08 UTC, LaamGinghong approved these changes

2020-05-13 06:33 UTC, CyberDamon approved these changes
nice

2020-05-29 02:25 UTC, merged