treeV2
gmfe/gmfe pull request #82
Opened 2020-06-12 09:03 UTC by lin2006yuo

1. TreeV2支持父节点查找
2. fix TreeV2经过筛选后点击全选，选择的是全部数据，而不是筛选后的数据

2020-06-15 11:20 UTC, LaamGinghong commented on packages/react/src/common/util.js
>   * 返回经过predicate筛选后的树
``` typescript

interface FilterGroupListLeaf {
  /**
   * 返回经过 predicate 筛选后的数
   * @param list 树状数组
   * @param predicate 断言
   * @param isPredicateParentNode 是否处理父节点，默认开启，若进行去反过滤时，要关闭
   */
  (
    list: FilterGroupListOptions[],
    predicate: (item: FilterGroupListOptions) => boolean,
    isPredicateParentNode: boolean
  ): FilterGroupListOptions[]
}

const filterGroupListLeaf: FilterGroupListLeaf = (
  list,
  predicate,
  isPredicateParentNode = true
) =>
  list
    .map((item) => {
      const copy = Object.assign({}, item)
      if (copy.children) {
        copy.children = filterGroupListLeaf(
          copy.children,
          predicate,
          isPredicateParentNode
        )
      }
      return copy
    })
    .filter((item) => {
      if (item.children) {
        return !!item.children.length
      } else {
        return predicate(item)
      }
    })
```

2020-06-17 00:50 UTC, CyberDamon requested changes

2020-06-17 00:50 UTC, chaoming56 commented on packages/react/src/common/util.js
> +export function filterGroupListLeaf(
是不是重写一个方法比较好?  处理父节点就不符合这个filterGroupListLeaf 函数命名了

2020-06-17 11:38 UTC, CyberDamon approved these changes

2020-06-23 02:34 UTC, merged